apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-gitops-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: duckdns-issuer
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik  # <--- AGREGÁ ESTA LÍNEA ACÁ
  tls:
  - hosts:
    - cloudtucu.duckdns.org
    secretName: cloudtucu-tls-cert
  rules:
  - host: cloudtucu.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-gitops-service
            port:
              number: 80
